console.log("   |    |    ")
console.log("   |    |    ")
console.log("   |    |    ")
console.log("_____________")
console.log("   |    |    ")
console.log("   |    |    ")
console.log("   |    |    ")
console.log("_____________")
console.log("   |    |    ")
console.log("   |    |    ")
console.log("   |    |    ")

